apiVersion: apps/v1
kind: Deployment
metadata:
  name: ch-deployment
spec:
  selector:
    matchLabels:
      app: ch
  replicas: 2
  template:
    metadata:
      labels:
        app: ch
    spec:
      containers:
        - name: ch
          image: chaden13/routerApp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8070

---
apiVersion: v1
kind: Service
metadata:
  name: ch-ssvc
spec:
  selector:
    app: ch
  ports:
    - protocol: "TCP"
      port: 8070
      targetPort: 8070
  type: NodePort
